---
- name: Update repositories cache (apt)
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Update repositories cache (pacman)
  pacman:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "pacman"

- name: Install dependencies (apt)
  apt:
    name: git
  when: ansible_pkg_mgr == "apt"

- name: Install dependencies (pacman)
  pacman:
    name: git
  when: ansible_pkg_mgr == "pacman"

- name: Set clone directory variable
  set_fact:
    zfs_snap_manager_clone_dir: "{{ global_cache_dir }}/python/src/github.com/khenderick/zfs-snap-manager"

- name: Clone zfs-snap-manager
  git:
    repo: "https://github.com/khenderick/zfs-snap-manager"
    dest: "{{ zfs_snap_manager_clone_dir }}"
    version: "v{{ zfs_snap_manager_version }}"
    force: true
  register: git

- name: Create library directory
  file:
    path: /usr/lib/zfs-snap-manager
    state: directory
    owner: root
    group: root
    mode: 0755
  when: git.changed

- name: Copy systemd service
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/system/zfs-snap-manager.service"
    dest: /etc/systemd/system/zfs-snap-manager.service
    force: true
    mode: 0644
    owner: root
    group: root
    remote_src: true
  when: git.changed

- name: Copy manager script
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/scripts/manager.py"
    dest: /usr/lib/zfs-snap-manager/manager.py
    force: true
    mode: 0755
    owner: root
    group: root
    remote_src: true
  when: git.changed

- name: Copy helper scripts
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/scripts/{{ item }}"
    dest: "/usr/lib/zfs-snap-manager/{{ item }}"
    force: true
    mode: 0644
    owner: root
    group: root
    remote_src: true
  with_items:
    - clean.py
    - helper.py
    - zfs.py
  when: git.changed