---
- name: Update repositories cache (apt)
  apt:
    update_cache: yes
  changed_when: False
  when: ansible_pkg_mgr == "apt"

- name: Update repositories cache (pacman)
  pacman:
    update_cache: yes
  changed_when: False
  when: ansible_pkg_mgr == "pacman"

- name: Install python2 (apt)
  apt:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "apt"
  with_items:
    - python
    - python-daemon

- name: Install python2 (pacman)
  pacman:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "pacman"
  with_items:
    - python2
    - python2-daemon

- name: Clone zfs-snap-manager
  git:
    repo: "https://github.com/SlothOfAnarchy/zfs-snap-manager"
    dest: "{{ zfs_snap_manager_clone_dir }}"
    force: True
  changed_when: False
  become: no
  run_once: True
  delegate_to: localhost

- name: Create library directory
  file:
    path: /usr/lib/zfs-snap-manager
    state: directory
    owner: root
    group: root
    mode: 0750
  notify: Enable and restart zfs-snap-manager

- name: Copy systemd service
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/system/zfs-snap-manager.service"
    dest: /etc/systemd/system/zfs-snap-manager.service
    force: True
    mode: 0644
    owner: root
    group: root
  notify: 
   - Reload systemd daemons
   - Enable and restart zfs-snap-manager

- name: Copy manager script
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/scripts/manager.py"
    dest: /usr/lib/zfs-snap-manager/manager.py
    force: True
    mode: 0755
    owner: root
    group: root
  notify: Enable and restart zfs-snap-manager

- name: Copy helper scripts
  copy:
    src: "{{ zfs_snap_manager_clone_dir }}/scripts/{{ item }}"
    dest: "/usr/lib/zfs-snap-manager/{{ item }}"
    force: True
    mode: 0644
    owner: root
    group: root
  with_items:
    - clean.py
    - helper.py
    - zfs.py
  notify: Enable and restart zfs-snap-manager
